-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

CREATE TABLE public.alternative_data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  telecom_provider character varying,
  phone_plan_type character varying,
  monthly_bill_average numeric,
  payment_consistency_score integer,
  data_usage_gb numeric,
  electricity_provider character varying,
  electricity_bill_average numeric,
  water_bill_average numeric,
  utility_payment_score integer,
  ecommerce_transactions integer,
  ecommerce_spend numeric,
  digital_wallet_usage character varying,
  app_usage_score integer,
  social_connectivity_score integer,
  professional_network_size integer,
  community_standing character varying,
  location_stability_score integer,
  schedule_consistency_score integer,
  spending_pattern_score integer,
  last_updated timestamp with time zone DEFAULT now(),
  CONSTRAINT alternative_data_pkey PRIMARY KEY (id),
  CONSTRAINT alternative_data_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.api_usage (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  partner_id uuid NOT NULL,
  endpoint character varying NOT NULL,
  method character varying NOT NULL,
  request_id character varying,
  request_body jsonb,
  response_code integer,
  response_body jsonb,
  response_time_ms integer,
  data_sources_accessed ARRAY,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_usage_pkey PRIMARY KEY (id),
  CONSTRAINT api_usage_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.assessments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  partner_id uuid NOT NULL,
  assessment_type USER-DEFINED NOT NULL,
  assessment_purpose text,
  requested_amount numeric,
  requested_tenure_months integer,
  credit_score integer,
  inclusion_score integer,
  fraud_score integer,
  behavioral_score integer,
  final_score integer,
  risk_category USER-DEFINED NOT NULL,
  probability_of_default numeric,
  loss_given_default numeric,
  exposure_at_default numeric,
  decision_outcome USER-DEFINED NOT NULL,
  approved_amount numeric,
  approved_tenure_months integer,
  interest_rate numeric,
  positive_factors jsonb,
  negative_factors jsonb,
  conditions ARRAY,
  model_version character varying,
  model_confidence numeric,
  processing_time_ms integer,
  data_sources_used jsonb,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  decision_by uuid,
  CONSTRAINT assessments_pkey PRIMARY KEY (id),
  CONSTRAINT assessments_decision_by_fkey FOREIGN KEY (decision_by) REFERENCES auth.users(id),
  CONSTRAINT assessments_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id),
  CONSTRAINT assessments_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.audit_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  partner_id uuid,
  action character varying NOT NULL,
  resource_type character varying,
  resource_id uuid,
  changes jsonb,
  metadata jsonb,
  ip_address inet,
  user_agent text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT audit_logs_pkey PRIMARY KEY (id),
  CONSTRAINT audit_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT audit_logs_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id)
);
CREATE TABLE public.blacklist (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  id_type USER-DEFINED,
  id_number_hash character varying,
  entity_id uuid,
  reason text NOT NULL,
  severity character varying NOT NULL,
  source character varying,
  added_by uuid,
  added_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  review_status character varying DEFAULT 'active'::character varying,
  reviewed_by uuid,
  review_notes text,
  CONSTRAINT blacklist_pkey PRIMARY KEY (id),
  CONSTRAINT blacklist_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id),
  CONSTRAINT blacklist_added_by_fkey FOREIGN KEY (added_by) REFERENCES auth.users(id),
  CONSTRAINT blacklist_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.company_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  company_name_ar character varying NOT NULL,
  company_name_en character varying NOT NULL,
  trade_name character varying,
  cr_number character varying NOT NULL UNIQUE,
  tax_number character varying,
  establishment_date date NOT NULL,
  company_type character varying,
  legal_structure character varying,
  industry_sector character varying,
  business_activity text,
  company_size character varying,
  paid_capital numeric,
  annual_revenue numeric,
  profit_margin numeric,
  employee_count integer,
  headquarters_address jsonb,
  mailing_address jsonb,
  phone character varying,
  email character varying,
  website character varying,
  ceo_name character varying,
  cfo_name character varying,
  authorized_signatories jsonb,
  board_members jsonb,
  ownership_structure jsonb,
  licenses jsonb,
  certifications jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT company_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT company_profiles_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.consents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  consent_type character varying NOT NULL,
  purpose text NOT NULL,
  data_categories ARRAY,
  granted boolean DEFAULT false,
  granted_at timestamp with time zone,
  expires_at timestamp with time zone,
  revoked_at timestamp with time zone,
  consent_channel character varying,
  ip_address inet,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT consents_pkey PRIMARY KEY (id),
  CONSTRAINT consents_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.credit_bureau_data (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  bureau_name character varying NOT NULL,
  report_number character varying,
  report_date date NOT NULL,
  bureau_score integer,
  score_band character varying,
  percentile_rank integer,
  total_accounts integer,
  active_accounts integer,
  closed_accounts integer,
  delinquent_accounts integer,
  total_credit_limit numeric,
  total_outstanding numeric,
  total_overdue numeric,
  credit_utilization numeric,
  debt_to_income numeric,
  payment_to_income numeric,
  oldest_account_months integer,
  average_account_age_months integer,
  recent_inquiries_count integer,
  defaults_count integer,
  writeoffs_count integer,
  bankruptcies_count integer,
  court_judgments_count integer,
  raw_report jsonb,
  created_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone,
  CONSTRAINT credit_bureau_data_pkey PRIMARY KEY (id),
  CONSTRAINT credit_bureau_data_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.entities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_type USER-DEFINED NOT NULL,
  status USER-DEFINED DEFAULT 'pending'::entity_status,
  risk_category USER-DEFINED DEFAULT 'unscoreable'::risk_category,
  credit_score integer CHECK (credit_score >= 300 AND credit_score <= 850),
  inclusion_score integer CHECK (inclusion_score >= 0 AND inclusion_score <= 100),
  fraud_score integer CHECK (fraud_score >= 0 AND fraud_score <= 100),
  behavioral_score integer,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  last_active_at timestamp with time zone,
  created_by uuid,
  search_vector tsvector,
  CONSTRAINT entities_pkey PRIMARY KEY (id),
  CONSTRAINT entities_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.feature_store (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  demographic_features jsonb,
  financial_features jsonb,
  behavioral_features jsonb,
  social_features jsonb,
  velocity_features jsonb,
  aggregated_features jsonb,
  engineered_features jsonb,
  computed_at timestamp with time zone DEFAULT now(),
  feature_version character varying,
  CONSTRAINT feature_store_pkey PRIMARY KEY (id),
  CONSTRAINT feature_store_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.financial_accounts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  account_type USER-DEFINED NOT NULL,
  account_number character varying,
  iban character varying,
  bank_code character varying,
  bank_name character varying,
  current_balance numeric,
  available_balance numeric,
  average_balance_3m numeric,
  average_balance_6m numeric,
  currency character varying DEFAULT 'SAR'::character varying,
  opening_date date,
  status character varying DEFAULT 'active'::character varying,
  is_primary boolean DEFAULT false,
  is_salary_account boolean DEFAULT false,
  consent_token character varying,
  consent_expiry timestamp with time zone,
  last_sync timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT financial_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT financial_accounts_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.fraud_indicators (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid,
  indicator_type character varying NOT NULL,
  severity character varying NOT NULL,
  confidence_score numeric,
  detected_by character varying,
  detection_method character varying,
  evidence jsonb,
  related_entities ARRAY,
  status character varying DEFAULT 'new'::character varying,
  investigated_by uuid,
  investigation_notes text,
  created_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT fraud_indicators_pkey PRIMARY KEY (id),
  CONSTRAINT fraud_indicators_investigated_by_fkey FOREIGN KEY (investigated_by) REFERENCES auth.users(id),
  CONSTRAINT fraud_indicators_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.identifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  id_type USER-DEFINED NOT NULL,
  id_number character varying NOT NULL,
  id_hash character varying DEFAULT encode(digest((id_number)::text, 'sha256'::text), 'hex'::text),
  nafath_verified boolean DEFAULT false,
  nafath_session_id character varying,
  nafath_verification_date timestamp with time zone,
  nafath_data jsonb,
  document_front_url text,
  document_back_url text,
  selfie_url text,
  verification_status USER-DEFINED DEFAULT 'unverified'::verification_status,
  verification_method character varying,
  verified_by uuid,
  issue_date date,
  expiry_date date,
  issuing_authority character varying,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT identifications_pkey PRIMARY KEY (id),
  CONSTRAINT identifications_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES auth.users(id),
  CONSTRAINT identifications_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.individual_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  full_name_ar character varying NOT NULL,
  full_name_en character varying NOT NULL,
  mother_name character varying,
  date_of_birth date NOT NULL,
  place_of_birth character varying,
  nationality character varying NOT NULL,
  gender character varying,
  blood_group character varying,
  mobile_primary character varying NOT NULL,
  mobile_verified boolean DEFAULT false,
  mobile_secondary character varying,
  email character varying,
  email_verified boolean DEFAULT false,
  address_national jsonb,
  province character varying,
  city character varying,
  district character varying,
  postal_code character varying,
  marital_status character varying,
  spouse_name character varying,
  dependents_count integer DEFAULT 0,
  family_income numeric,
  employment_type character varying,
  employer_name character varying,
  employer_id character varying,
  occupation character varying,
  job_title character varying,
  work_sector character varying,
  years_employed integer,
  monthly_salary numeric,
  monthly_income numeric,
  other_income numeric,
  total_assets numeric,
  total_liabilities numeric,
  monthly_obligations numeric,
  education_level character varying,
  university character varying,
  graduation_year integer,
  preferred_language character varying DEFAULT 'ar'::character varying,
  digital_literacy_score integer,
  financial_literacy_score integer,
  has_bank_account boolean DEFAULT false,
  has_smartphone boolean DEFAULT false,
  internet_access character varying,
  social_media_active boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT individual_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT individual_profiles_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
CREATE TABLE public.lending_decisions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  assessment_id uuid NOT NULL,
  entity_id uuid NOT NULL,
  partner_id uuid NOT NULL,
  product_type character varying,
  product_id character varying,
  loan_amount numeric NOT NULL,
  tenure_months integer NOT NULL,
  interest_rate numeric,
  monthly_payment numeric,
  status character varying DEFAULT 'pending'::character varying,
  disbursement_date date,
  maturity_date date,
  payments_made integer DEFAULT 0,
  payments_remaining integer,
  outstanding_balance numeric,
  days_past_due integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lending_decisions_pkey PRIMARY KEY (id),
  CONSTRAINT lending_decisions_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id),
  CONSTRAINT lending_decisions_partner_id_fkey FOREIGN KEY (partner_id) REFERENCES public.partners(id),
  CONSTRAINT lending_decisions_assessment_id_fkey FOREIGN KEY (assessment_id) REFERENCES public.assessments(id)
);
CREATE TABLE public.ml_models (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  model_name character varying NOT NULL,
  model_type character varying NOT NULL,
  version character varying NOT NULL,
  accuracy numeric,
  precision numeric,
  recall numeric,
  f1_score numeric,
  auc_roc numeric,
  status character varying DEFAULT 'training'::character varying,
  deployed_at timestamp with time zone,
  retired_at timestamp with time zone,
  hyperparameters jsonb,
  feature_importance jsonb,
  training_data_info jsonb,
  model_path text,
  created_at timestamp with time zone DEFAULT now(),
  created_by uuid,
  CONSTRAINT ml_models_pkey PRIMARY KEY (id),
  CONSTRAINT ml_models_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.notification_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  template_name character varying NOT NULL UNIQUE,
  template_type character varying NOT NULL,
  subject character varying,
  body_ar text NOT NULL,
  body_en text NOT NULL,
  variables ARRAY,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid,
  template_id uuid,
  channel character varying NOT NULL,
  recipient character varying NOT NULL,
  subject character varying,
  body text,
  status character varying DEFAULT 'pending'::character varying,
  sent_at timestamp with time zone,
  delivered_at timestamp with time zone,
  read_at timestamp with time zone,
  failed_at timestamp with time zone,
  failure_reason text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id),
  CONSTRAINT notifications_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.notification_templates(id)
);
CREATE TABLE public.partners (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  partner_name character varying NOT NULL,
  partner_name_ar character varying,
  partner_type USER-DEFINED NOT NULL,
  cr_number character varying,
  api_key character varying NOT NULL UNIQUE,
  api_secret character varying NOT NULL,
  jwt_secret character varying,
  integration_type USER-DEFINED DEFAULT 'api'::integration_type,
  webhook_url text,
  callback_url text,
  ip_whitelist ARRAY,
  permissions jsonb DEFAULT '[]'::jsonb,
  allowed_products ARRAY,
  rate_limit_per_second integer DEFAULT 10,
  rate_limit_per_minute integer DEFAULT 100,
  rate_limit_per_hour integer DEFAULT 1000,
  monthly_quota integer DEFAULT 10000,
  current_month_usage integer DEFAULT 0,
  total_assessments integer DEFAULT 0,
  total_approvals integer DEFAULT 0,
  pricing_tier character varying DEFAULT 'standard'::character varying,
  contract_start_date date,
  contract_end_date date,
  billing_details jsonb,
  status character varying DEFAULT 'pending'::character varying,
  activated_at timestamp with time zone,
  suspended_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT partners_pkey PRIMARY KEY (id)
);
CREATE TABLE public.transactions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  entity_id uuid NOT NULL,
  account_id uuid,
  transaction_type USER-DEFINED NOT NULL,
  amount numeric NOT NULL,
  currency character varying DEFAULT 'SAR'::character varying,
  reference_number character varying,
  description text,
  merchant_name character varying,
  merchant_category character varying,
  sender_account character varying,
  sender_name character varying,
  receiver_account character varying,
  receiver_name character varying,
  transaction_date timestamp with time zone NOT NULL,
  posting_date timestamp with time zone,
  value_date timestamp with time zone,
  category character varying,
  is_recurring boolean DEFAULT false,
  is_suspicious boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transactions_pkey PRIMARY KEY (id),
  CONSTRAINT transactions_account_id_fkey FOREIGN KEY (account_id) REFERENCES public.financial_accounts(id),
  CONSTRAINT transactions_entity_id_fkey FOREIGN KEY (entity_id) REFERENCES public.entities(id)
);
