| export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      alternative_data: {\n        Row: {\n          id: string;
          entity_id: string;
          telecom_provider: string | null;
          phone_plan_type: string | null;
          monthly_bill_average: number | null;
          payment_consistency_score: number | null;
          data_usage_gb: number | null;
          electricity_provider: string | null;
          electricity_bill_average: number | null;
          water_bill_average: number | null;
          utility_payment_score: number | null;
          ecommerce_transactions: number | null;
          ecommerce_spend: number | null;
          digital_wallet_usage: string | null;
          app_usage_score: number | null;
          social_connectivity_score: number | null;
          professional_network_size: number | null;
          community_standing: string | null;
          location_stability_score: number | null;
          schedule_consistency_score: number | null;
          spending_pattern_score: number | null;
          last_updated: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          telecom_provider?: string | null;
          phone_plan_type?: string | null;
          monthly_bill_average?: number | null;
          payment_consistency_score?: number | null;
          data_usage_gb?: number | null;
          electricity_provider?: string | null;
          electricity_bill_average?: number | null;
          water_bill_average?: number | null;
          utility_payment_score?: number | null;
          ecommerce_transactions?: number | null;
          ecommerce_spend?: number | null;
          digital_wallet_usage?: string | null;
          app_usage_score?: number | null;
          social_connectivity_score?: number | null;
          professional_network_size?: number | null;
          community_standing?: string | null;
          location_stability_score?: number | null;
          schedule_consistency_score?: number | null;
          spending_pattern_score?: number | null;
          last_updated?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          telecom_provider?: string | null;
          phone_plan_type?: string | null;
          monthly_bill_average?: number | null;
          payment_consistency_score?: number | null;
          data_usage_gb?: number | null;
          electricity_provider?: string | null;
          electricity_bill_average?: number | null;
          water_bill_average?: number | null;
          utility_payment_score?: number | null;
          ecommerce_transactions?: number | null;
          ecommerce_spend?: number | null;
          digital_wallet_usage?: string | null;
          app_usage_score?: number | null;
          social_connectivity_score?: number | null;
          professional_network_size?: number | null;
          community_standing?: string | null;
          location_stability_score?: number | null;
          schedule_consistency_score?: number | null;
          spending_pattern_score?: number | null;
          last_updated?: string | null;\n        };\n      };
      api_usage: {\n        Row: {\n          id: string;
          partner_id: string;
          endpoint: string;
          method: string;
          request_id: string | null;
          request_body: Json | null;
          response_code: number | null;
          response_body: Json | null;
          response_time_ms: number | null;
          data_sources_accessed: string[] | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string | null;\n        };\n        Insert: {\n          id?: string;
          partner_id: string;
          endpoint: string;
          method: string;
          request_id?: string | null;
          request_body?: Json | null;
          response_code?: number | null;
          response_body?: Json | null;
          response_time_ms?: number | null;
          data_sources_accessed?: string[] | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string | null;\n        };\n        Update: {\n          id?: string;
          partner_id?: string;
          endpoint?: string;
          method?: string;
          request_id?: string | null;
          request_body?: Json | null;
          response_code?: number | null;
          response_body?: Json | null;
          response_time_ms?: number | null;
          data_sources_accessed?: string[] | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string | null;\n        };\n      };
      assessments: {\n        Row: {\n          id: string;
          entity_id: string;
          partner_id: string;
          assessment_type: Database["public"]["Enums"]["assessment_type"];
          assessment_purpose: string | null;
          requested_amount: number | null;
          requested_tenure_months: number | null;
          credit_score: number | null;
          inclusion_score: number | null;
          fraud_score: number | null;
          behavioral_score: number | null;
          final_score: number | null;
          risk_category: Database["public"]["Enums"]["risk_category"];
          probability_of_default: number | null;
          loss_given_default: number | null;
          exposure_at_default: number | null;
          decision_outcome: Database["public"]["Enums"]["decision_outcome"];
          approved_amount: number | null;
          approved_tenure_months: number | null;
          interest_rate: number | null;
          positive_factors: Json | null;
          negative_factors: Json | null;
          conditions: string[] | null;
          model_version: string | null;
          model_confidence: number | null;
          processing_time_ms: number | null;
          data_sources_used: Json | null;
          created_at: string | null;
          expires_at: string | null;
          decision_by: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          partner_id: string;
          assessment_type: Database["public"]["Enums"]["assessment_type"];
          assessment_purpose?: string | null;
          requested_amount?: number | null;
          requested_tenure_months?: number | null;
          credit_score?: number | null;
          inclusion_score?: number | null;
          fraud_score?: number | null;
          behavioral_score?: number | null;
          final_score?: number | null;
          risk_category: Database["public"]["Enums"]["risk_category"];
          probability_of_default?: number | null;
          loss_given_default?: number | null;
          exposure_at_default?: number | null;
          decision_outcome: Database["public"]["Enums"]["decision_outcome"];
          approved_amount?: number | null;
          approved_tenure_months?: number | null;
          interest_rate?: number | null;
          positive_factors?: Json | null;
          negative_factors?: Json | null;
          conditions?: string[] | null;
          model_version?: string | null;
          model_confidence?: number | null;
          processing_time_ms?: number | null;
          data_sources_used?: Json | null;
          created_at?: string | null;
          expires_at?: string | null;
          decision_by?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          partner_id?: string;
          assessment_type?: Database["public"]["Enums"]["assessment_type"];
          assessment_purpose?: string | null;
          requested_amount?: number | null;
          requested_tenure_months?: number | null;
          credit_score?: number | null;
          inclusion_score?: number | null;
          fraud_score?: number | null;
          behavioral_score?: number | null;
          final_score?: number | null;
          risk_category?: Database["public"]["Enums"]["risk_category"];
          probability_of_default?: number | null;
          loss_given_default?: number | null;
          exposure_at_default?: number | null;
          decision_outcome?: Database["public"]["Enums"]["decision_outcome"];
          approved_amount?: number | null;
          approved_tenure_months?: number | null;
          interest_rate?: number | null;
          positive_factors?: Json | null;
          negative_factors?: Json | null;
          conditions?: string[] | null;
          model_version?: string | null;
          model_confidence?: number | null;
          processing_time_ms?: number | null;
          data_sources_used?: Json | null;
          created_at?: string | null;
          expires_at?: string | null;
          decision_by?: string | null;\n        };\n      };
      audit_logs: {\n        Row: {\n          id: string;
          user_id: string | null;
          partner_id: string | null;
          action: string;
          resource_type: string | null;
          resource_id: string | null;
          changes: Json | null;
          metadata: Json | null;
          ip_address: string | null;
          user_agent: string | null;
          created_at: string | null;\n        };\n        Insert: {\n          id?: string;
          user_id?: string | null;
          partner_id?: string | null;
          action: string;
          resource_type?: string | null;
          resource_id?: string | null;
          changes?: Json | null;
          metadata?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string | null;\n        };\n        Update: {\n          id?: string;
          user_id?: string | null;
          partner_id?: string | null;
          action?: string;
          resource_type?: string | null;
          resource_id?: string | null;
          changes?: Json | null;
          metadata?: Json | null;
          ip_address?: string | null;
          user_agent?: string | null;
          created_at?: string | null;\n        };\n      };
      blacklist: {\n        Row: {\n          id: string;
          id_type: Database["public"]["Enums"]["id_type"] | null;
          id_number_hash: string | null;
          entity_id: string | null;
          reason: string;
          severity: string;
          source: string | null;
          added_by: string | null;
          added_at: string | null;
          expires_at: string | null;
          review_status: string | null;
          reviewed_by: string | null;
          review_notes: string | null;\n        };\n        Insert: {\n          id?: string;
          id_type?: Database["public"]["Enums"]["id_type"] | null;
          id_number_hash?: string | null;
          entity_id?: string | null;
          reason: string;
          severity: string;
          source?: string | null;
          added_by?: string | null;
          added_at?: string | null;
          expires_at?: string | null;
          review_status?: string | null;
          reviewed_by?: string | null;
          review_notes?: string | null;\n        };\n        Update: {\n          id?: string;
          id_type?: Database["public"]["Enums"]["id_type"] | null;
          id_number_hash?: string | null;
          entity_id?: string | null;
          reason?: string;
          severity?: string;
          source?: string | null;
          added_by?: string | null;
          added_at?: string | null;
          expires_at?: string | null;
          review_status?: string | null;
          reviewed_by?: string | null;
          review_notes?: string | null;\n        };\n      };
      company_profiles: {\n        Row: {\n          id: string;
          entity_id: string;
          company_name_ar: string;
          company_name_en: string;
          trade_name: string | null;
          cr_number: string;
          tax_number: string | null;
          establishment_date: string;
          company_type: string | null;
          legal_structure: string | null;
          industry_sector: string | null;
          business_activity: string | null;
          company_size: string | null;
          paid_capital: number | null;
          annual_revenue: number | null;
          profit_margin: number | null;
          employee_count: number | null;
          headquarters_address: Json | null;
          mailing_address: Json | null;
          phone: string | null;
          email: string | null;
          website: string | null;
          ceo_name: string | null;
          cfo_name: string | null;
          authorized_signatories: Json | null;
          board_members: Json | null;
          ownership_structure: Json | null;
          licenses: Json | null;
          certifications: Json | null;
          created_at: string | null;
          updated_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          company_name_ar: string;
          company_name_en: string;
          trade_name?: string | null;
          cr_number: string;
          tax_number?: string | null;
          establishment_date: string;
          company_type?: string | null;
          legal_structure?: string | null;
          industry_sector?: string | null;
          business_activity?: string | null;
          company_size?: string | null;
          paid_capital?: number | null;
          annual_revenue?: number | null;
          profit_margin?: number | null;
          employee_count?: number | null;
          headquarters_address?: Json | null;
          mailing_address?: Json | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          ceo_name?: string | null;
          cfo_name?: string | null;
          authorized_signatories?: Json | null;
          board_members?: Json | null;
          ownership_structure?: Json | null;
          licenses?: Json | null;
          certifications?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          company_name_ar?: string;
          company_name_en?: string;
          trade_name?: string | null;
          cr_number?: string;
          tax_number?: string | null;
          establishment_date?: string;
          company_type?: string | null;
          legal_structure?: string | null;
          industry_sector?: string | null;
          business_activity?: string | null;
          company_size?: string | null;
          paid_capital?: number | null;
          annual_revenue?: number | null;
          profit_margin?: number | null;
          employee_count?: number | null;
          headquarters_address?: Json | null;
          mailing_address?: Json | null;
          phone?: string | null;
          email?: string | null;
          website?: string | null;
          ceo_name?: string | null;
          cfo_name?: string | null;
          authorized_signatories?: Json | null;
          board_members?: Json | null;
          ownership_structure?: Json | null;
          licenses?: Json | null;
          certifications?: Json | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n      };
      consents: {\n        Row: {\n          id: string;
          entity_id: string;
          consent_type: string;
          purpose: string;
          data_categories: string[] | null;
          granted: boolean | null;
          granted_at: string | null;
          expires_at: string | null;
          revoked_at: string | null;
          consent_channel: string | null;
          ip_address: string | null;
          created_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          consent_type: string;
          purpose: string;
          data_categories?: string[] | null;
          granted?: boolean | null;
          granted_at?: string | null;
          expires_at?: string | null;
          revoked_at?: string | null;
          consent_channel?: string | null;
          ip_address?: string | null;
          created_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          consent_type?: string;
          purpose?: string;
          data_categories?: string[] | null;
          granted?: boolean | null;
          granted_at?: string | null;
          expires_at?: string | null;
          revoked_at?: string | null;
          consent_channel?: string | null;
          ip_address?: string | null;
          created_at?: string | null;\n        };\n      };
      credit_bureau_data: {\n        Row: {\n          id: string;
          entity_id: string;
          bureau_name: string;
          report_number: string | null;
          report_date: string;
          bureau_score: number | null;
          score_band: string | null;
          percentile_rank: number | null;
          total_accounts: number | null;
          active_accounts: number | null;
          closed_accounts: number | null;
          delinquent_accounts: number | null;
          total_credit_limit: number | null;
          total_outstanding: number | null;
          total_overdue: number | null;
          credit_utilization: number | null;
          debt_to_income: number | null;
          payment_to_income: number | null;
          oldest_account_months: number | null;
          average_account_age_months: number | null;
          recent_inquiries_count: number | null;
          defaults_count: number | null;
          writeoffs_count: number | null;
          bankruptcies_count: number | null;
          court_judgments_count: number | null;
          raw_report: Json | null;
          created_at: string | null;
          expires_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          bureau_name: string;
          report_number?: string | null;
          report_date: string;
          bureau_score?: number | null;
          score_band?: string | null;
          percentile_rank?: number | null;
          total_accounts?: number | null;
          active_accounts?: number | null;
          closed_accounts?: number | null;
          delinquent_accounts?: number | null;
          total_credit_limit?: number | null;
          total_outstanding?: number | null;
          total_overdue?: number | null;
          credit_utilization?: number | null;
          debt_to_income?: number | null;
          payment_to_income?: number | null;
          oldest_account_months?: number | null;
          average_account_age_months?: number | null;
          recent_inquiries_count?: number | null;
          defaults_count?: number | null;
          writeoffs_count?: number | null;
          bankruptcies_count?: number | null;
          court_judgments_count?: number | null;
          raw_report?: Json | null;
          created_at?: string | null;
          expires_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          bureau_name?: string;
          report_number?: string | null;
          report_date?: string;
          bureau_score?: number | null;
          score_band?: string | null;
          percentile_rank?: number | null;
          total_accounts?: number | null;
          active_accounts?: number | null;
          closed_accounts?: number | null;
          delinquent_accounts?: number | null;
          total_credit_limit?: number | null;
          total_outstanding?: number | null;
          total_overdue?: number | null;
          credit_utilization?: number | null;
          debt_to_income?: number | null;
          payment_to_income?: number | null;
          oldest_account_months?: number | null;
          average_account_age_months?: number | null;
          recent_inquiries_count?: number | null;
          defaults_count?: number | null;
          writeoffs_count?: number | null;
          bankruptcies_count?: number | null;
          court_judgments_count?: number | null;
          raw_report?: Json | null;
          created_at?: string | null;
          expires_at?: string | null;\n        };\n      };
      entities: {\n        Row: {\n          id: string;
          entity_type: Database["public"]["Enums"]["entity_type"];
          status: Database["public"]["Enums"]["entity_status"] | null;
          risk_category: Database["public"]["Enums"]["risk_category"] | null;
          credit_score: number | null;
          inclusion_score: number | null;
          fraud_score: number | null;
          behavioral_score: number | null;
          created_at: string | null;
          updated_at: string | null;
          verified_at: string | null;
          last_active_at: string | null;
          created_by: string | null;
          search_vector: any | null;\n        };\n        Insert: {\n          id?: string;
          entity_type: Database["public"]["Enums"]["entity_type"];
          status?: Database["public"]["Enums"]["entity_status"] | null;
          risk_category?: Database["public"]["Enums"]["risk_category"] | null;
          credit_score?: number | null;
          inclusion_score?: number | null;
          fraud_score?: number | null;
          behavioral_score?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          verified_at?: string | null;
          last_active_at?: string | null;
          created_by?: string | null;
          search_vector?: any | null;\n        };\n        Update: {\n          id?: string;
          entity_type?: Database["public"]["Enums"]["entity_type"];
          status?: Database["public"]["Enums"]["entity_status"] | null;
          risk_category?: Database["public"]["Enums"]["risk_category"] | null;
          credit_score?: number | null;
          inclusion_score?: number | null;
          fraud_score?: number | null;
          behavioral_score?: number | null;
          created_at?: string | null;
          updated_at?: string | null;
          verified_at?: string | null;
          last_active_at?: string | null;
          created_by?: string | null;
          search_vector?: any | null;\n        };\n      };
      feature_store: {\n        Row: {\n          id: string;
          entity_id: string;
          demographic_features: Json | null;
          financial_features: Json | null;
          behavioral_features: Json | null;
          social_features: Json | null;
          velocity_features: Json | null;
          aggregated_features: Json | null;
          engineered_features: Json | null;
          computed_at: string | null;
          feature_version: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          demographic_features?: Json | null;
          financial_features?: Json | null;
          behavioral_features?: Json | null;
          social_features?: Json | null;
          velocity_features?: Json | null;
          aggregated_features?: Json | null;
          engineered_features?: Json | null;
          computed_at?: string | null;
          feature_version?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          demographic_features?: Json | null;
          financial_features?: Json | null;
          behavioral_features?: Json | null;
          social_features?: Json | null;
          velocity_features?: Json | null;
          aggregated_features?: Json | null;
          engineered_features?: Json | null;
          computed_at?: string | null;
          feature_version?: string | null;\n        };\n      };
      financial_accounts: {\n        Row: {\n          id: string;
          entity_id: string;
          account_type: Database["public"]["Enums"]["account_type"];
          account_number: string | null;
          iban: string | null;
          bank_code: string | null;
          bank_name: string | null;
          current_balance: number | null;
          available_balance: number | null;
          average_balance_3m: number | null;
          average_balance_6m: number | null;
          currency: string | null;
          opening_date: string | null;
          status: string | null;
          is_primary: boolean | null;
          is_salary_account: boolean | null;
          consent_token: string | null;
          consent_expiry: string | null;
          last_sync: string | null;
          created_at: string | null;
          updated_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          account_type: Database["public"]["Enums"]["account_type"];
          account_number?: string | null;
          iban?: string | null;
          bank_code?: string | null;
          bank_name?: string | null;
          current_balance?: number | null;
          available_balance?: number | null;
          average_balance_3m?: number | null;
          average_balance_6m?: number | null;
          currency?: string | null;
          opening_date?: string | null;
          status?: string | null;
          is_primary?: boolean | null;
          is_salary_account?: boolean | null;
          consent_token?: string | null;
          consent_expiry?: string | null;
          last_sync?: string | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          account_type?: Database["public"]["Enums"]["account_type"];
          account_number?: string | null;
          iban?: string | null;
          bank_code?: string | null;
          bank_name?: string | null;
          current_balance?: number | null;
          available_balance?: number | null;
          average_balance_3m?: number | null;
          average_balance_6m?: number | null;
          currency?: string | null;
          opening_date?: string | null;
          status?: string | null;
          is_primary?: boolean | null;
          is_salary_account?: boolean | null;
          consent_token?: string | null;
          consent_expiry?: string | null;
          last_sync?: string | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n      };
      fraud_indicators: {\n        Row: {\n          id: string;
          entity_id: string | null;
          indicator_type: string;
          severity: string;
          confidence_score: number | null;
          detected_by: string | null;
          detection_method: string | null;
          evidence: Json | null;
          related_entities: string[] | null;
          status: string | null;
          investigated_by: string | null;
          investigation_notes: string | null;
          created_at: string | null;
          resolved_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id?: string | null;
          indicator_type: string;
          severity: string;
          confidence_score?: number | null;
          detected_by?: string | null;
          detection_method?: string | null;
          evidence?: Json | null;
          related_entities?: string[] | null;
          status?: string | null;
          investigated_by?: string | null;
          investigation_notes?: string | null;
          created_at?: string | null;
          resolved_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string | null;
          indicator_type?: string;
          severity?: string;
          confidence_score?: number | null;
          detected_by?: string | null;
          detection_method?: string | null;
          evidence?: Json | null;
          related_entities?: string[] | null;
          status?: string | null;
          investigated_by?: string | null;
          investigation_notes?: string | null;
          created_at?: string | null;
          resolved_at?: string | null;\n        };\n      };
      identifications: {\n        Row: {\n          id: string;
          entity_id: string;
          id_type: Database["public"]["Enums"]["id_type"];
          id_number: string;
          id_hash: string | null;
          nafath_verified: boolean | null;
          nafath_session_id: string | null;
          nafath_verification_date: string | null;
          nafath_data: Json | null;
          document_front_url: string | null;
          document_back_url: string | null;
          selfie_url: string | null;
          verification_status: Database["public"]["Enums"]["verification_status"] | null;
          verification_method: string | null;
          verified_by: string | null;
          issue_date: string | null;
          expiry_date: string | null;
          issuing_authority: string | null;
          created_at: string | null;
          updated_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          id_type: Database["public"]["Enums"]["id_type"];
          id_number: string;
          id_hash?: string | null;
          nafath_verified?: boolean | null;
          nafath_session_id?: string | null;
          nafath_verification_date?: string | null;
          nafath_data?: Json | null;
          document_front_url?: string | null;
          document_back_url?: string | null;
          selfie_url?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status"] | null;
          verification_method?: string | null;
          verified_by?: string | null;
          issue_date?: string | null;
          expiry_date?: string | null;
          issuing_authority?: string | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          id_type?: Database["public"]["Enums"]["id_type"];
          id_number?: string;
          id_hash?: string | null;
          nafath_verified?: boolean | null;
          nafath_session_id?: string | null;
          nafath_verification_date?: string | null;
          nafath_data?: Json | null;
          document_front_url?: string | null;
          document_back_url?: string | null;
          selfie_url?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status"] | null;
          verification_method?: string | null;
          verified_by?: string | null;
          issue_date?: string | null;
          expiry_date?: string | null;
          issuing_authority?: string | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n      };
      individual_profiles: {\n        Row: {\n          id: string;
          entity_id: string;
          full_name_ar: string;
          full_name_en: string;
          mother_name: string | null;
          date_of_birth: string;
          place_of_birth: string | null;
          nationality: string;
          gender: string | null;
          blood_group: string | null;
          mobile_primary: string;
          mobile_verified: boolean | null;
          mobile_secondary: string | null;
          email: string | null;
          email_verified: boolean | null;
          address_national: Json | null;
          province: string | null;
          city: string | null;
          district: string | null;
          postal_code: string | null;
          marital_status: string | null;
          spouse_name: string | null;
          dependents_count: number | null;
          family_income: number | null;
          employment_type: string | null;
          employer_name: string | null;
          employer_id: string | null;
          occupation: string | null;
          job_title: string | null;
          work_sector: string | null;
          years_employed: number | null;
          monthly_salary: number | null;
          monthly_income: number | null;
          other_income: number | null;
          total_assets: number | null;
          total_liabilities: number | null;
          monthly_obligations: number | null;
          education_level: string | null;
          university: string | null;
          graduation_year: number | null;
          preferred_language: string | null;
          digital_literacy_score: number | null;
          financial_literacy_score: number | null;
          has_bank_account: boolean | null;
          has_smartphone: boolean | null;
          internet_access: string | null;
          social_media_active: boolean | null;
          created_at: string | null;
          updated_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          full_name_ar: string;
          full_name_en: string;
          mother_name?: string | null;
          date_of_birth: string;
          place_of_birth?: string | null;
          nationality: string;
          gender?: string | null;
          blood_group?: string | null;
          mobile_primary: string;
          mobile_verified?: boolean | null;
          mobile_secondary?: string | null;
          email?: string | null;
          email_verified?: boolean | null;
          address_national?: Json | null;
          province?: string | null;
          city?: string | null;
          district?: string | null;
          postal_code?: string | null;
          marital_status?: string | null;
          spouse_name?: string | null;
          dependents_count?: number | null;
          family_income?: number | null;
          employment_type?: string | null;
          employer_name?: string | null;
          employer_id?: string | null;
          occupation?: string | null;
          job_title?: string | null;
          work_sector?: string | null;
          years_employed?: number | null;
          monthly_salary?: number | null;
          monthly_income?: number | null;
          other_income?: number | null;
          total_assets?: number | null;
          total_liabilities?: number | null;
          monthly_obligations?: number | null;
          education_level?: string | null;
          university?: string | null;
          graduation_year?: number | null;
          preferred_language?: string | null;
          digital_literacy_score?: number | null;
          financial_literacy_score?: number | null;
          has_bank_account?: boolean | null;
          has_smartphone?: boolean | null;
          internet_access?: string | null;
          social_media_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          full_name_ar?: string;
          full_name_en?: string;
          mother_name?: string | null;
          date_of_birth?: string;
          place_of_birth?: string | null;
          nationality?: string;
          gender?: string | null;
          blood_group?: string | null;
          mobile_primary?: string;
          mobile_verified?: boolean | null;
          mobile_secondary?: string | null;
          email?: string | null;
          email_verified?: boolean | null;
          address_national?: Json | null;
          province?: string | null;
          city?: string | null;
          district?: string | null;
          postal_code?: string | null;
          marital_status?: string | null;
          spouse_name?: string | null;
          dependents_count?: number | null;
          family_income?: number | null;
          employment_type?: string | null;
          employer_name?: string | null;
          employer_id?: string | null;
          occupation?: string | null;
          job_title?: string | null;
          work_sector?: string | null;
          years_employed?: number | null;
          monthly_salary?: number | null;
          monthly_income?: number | null;
          other_income?: number | null;
          total_assets?: number | null;
          total_liabilities?: number | null;
          monthly_obligations?: number | null;
          education_level?: string | null;
          university?: string | null;
          graduation_year?: number | null;
          preferred_language?: string | null;
          digital_literacy_score?: number | null;
          financial_literacy_score?: number | null;
          has_bank_account?: boolean | null;
          has_smartphone?: boolean | null;
          internet_access?: string | null;
          social_media_active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n      };
      lending_decisions: {\n        Row: {\n          id: string;
          assessment_id: string;
          entity_id: string;
          partner_id: string;
          product_type: string | null;
          product_id: string | null;
          loan_amount: number;
          tenure_months: number;
          interest_rate: number | null;
          monthly_payment: number | null;
          status: string | null;
          disbursement_date: string | null;
          maturity_date: string | null;
          payments_made: number | null;
          payments_remaining: number | null;
          outstanding_balance: number | null;
          days_past_due: number | null;
          created_at: string | null;
          updated_at: string | null;\n        };\n        Insert: {\n          id?: string;
          assessment_id: string;
          entity_id: string;
          partner_id: string;
          product_type?: string | null;
          product_id?: string | null;
          loan_amount: number;
          tenure_months: number;
          interest_rate?: number | null;
          monthly_payment?: number | null;
          status?: string | null;
          disbursement_date?: string | null;
          maturity_date?: string | null;
          payments_made?: number | null;
          payments_remaining?: number | null;
          outstanding_balance?: number | null;
          days_past_due?: number | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n        Update: {\n          id?: string;
          assessment_id?: string;
          entity_id?: string;
          partner_id?: string;
          product_type?: string | null;
          product_id?: string | null;
          loan_amount?: number;
          tenure_months?: number;
          interest_rate?: number | null;
          monthly_payment?: number | null;
          status?: string | null;
          disbursement_date?: string | null;
          maturity_date?: string | null;
          payments_made?: number | null;
          payments_remaining?: number | null;
          outstanding_balance?: number | null;
          days_past_due?: number | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n      };
      ml_models: {\n        Row: {\n          id: string;
          model_name: string;
          model_type: string;
          version: string;
          accuracy: number | null;
          precision: number | null;
          recall: number | null;
          f1_score: number | null;
          auc_roc: number | null;
          status: string | null;
          deployed_at: string | null;
          retired_at: string | null;
          hyperparameters: Json | null;
          feature_importance: Json | null;
          training_data_info: Json | null;
          model_path: string | null;
          created_at: string | null;
          created_by: string | null;\n        };\n        Insert: {\n          id?: string;
          model_name: string;
          model_type: string;
          version: string;
          accuracy?: number | null;
          precision?: number | null;
          recall?: number | null;
          f1_score?: number | null;
          auc_roc?: number | null;
          status?: string | null;
          deployed_at?: string | null;
          retired_at?: string | null;
          hyperparameters?: Json | null;
          feature_importance?: Json | null;
          training_data_info?: Json | null;
          model_path?: string | null;
          created_at?: string | null;
          created_by?: string | null;\n        };\n        Update: {\n          id?: string;
          model_name?: string;
          model_type?: string;
          version?: string;
          accuracy?: number | null;
          precision?: number | null;
          recall?: number | null;
          f1_score?: number | null;
          auc_roc?: number | null;
          status?: string | null;
          deployed_at?: string | null;
          retired_at?: string | null;
          hyperparameters?: Json | null;
          feature_importance?: Json | null;
          training_data_info?: Json | null;
          model_path?: string | null;
          created_at?: string | null;
          created_by?: string | null;\n        };\n      };
      notification_templates: {\n        Row: {\n          id: string;
          template_name: string;
          template_type: string;
          subject: string | null;
          body_ar: string;
          body_en: string;
          variables: string[] | null;
          active: boolean | null;
          created_at: string | null;
          updated_at: string | null;\n        };\n        Insert: {\n          id?: string;
          template_name: string;
          template_type: string;
          subject?: string | null;
          body_ar: string;
          body_en: string;
          variables?: string[] | null;
          active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n        Update: {\n          id?: string;
          template_name?: string;
          template_type?: string;
          subject?: string | null;
          body_ar?: string;
          body_en?: string;
          variables?: string[] | null;
          active?: boolean | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n      };
      notifications: {\n        Row: {\n          id: string;
          entity_id: string | null;
          template_id: string | null;
          channel: string;
          recipient: string;
          subject: string | null;
          body: string | null;
          status: string | null;
          sent_at: string | null;
          delivered_at: string | null;
          read_at: string | null;
          failed_at: string | null;
          failure_reason: string | null;
          created_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id?: string | null;
          template_id?: string | null;
          channel: string;
          recipient: string;
          subject?: string | null;
          body?: string | null;
          status?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          failed_at?: string | null;
          failure_reason?: string | null;
          created_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string | null;
          template_id?: string | null;
          channel?: string;
          recipient?: string;
          subject?: string | null;
          body?: string | null;
          status?: string | null;
          sent_at?: string | null;
          delivered_at?: string | null;
          read_at?: string | null;
          failed_at?: string | null;
          failure_reason?: string | null;
          created_at?: string | null;\n        };\n      };
      partners: {\n        Row: {\n          id: string;
          partner_name: string;
          partner_name_ar: string | null;
          partner_type: Database["public"]["Enums"]["partner_type"];
          cr_number: string | null;
          api_key: string;
          api_secret: string;
          jwt_secret: string | null;
          integration_type: Database["public"]["Enums"]["integration_type"] | null;
          webhook_url: string | null;
          callback_url: string | null;
          ip_whitelist: string[] | null;
          permissions: Json | null;
          allowed_products: string[] | null;
          rate_limit_per_second: number | null;
          rate_limit_per_minute: number | null;
          rate_limit_per_hour: number | null;
          monthly_quota: number | null;
          current_month_usage: number | null;
          total_assessments: number | null;
          total_approvals: number | null;
          pricing_tier: string | null;
          contract_start_date: string | null;
          contract_end_date: string | null;
          billing_details: Json | null;
          status: string | null;
          activated_at: string | null;
          suspended_at: string | null;
          created_at: string | null;
          updated_at: string | null;\n        };\n        Insert: {\n          id?: string;
          partner_name: string;
          partner_name_ar?: string | null;
          partner_type: Database["public"]["Enums"]["partner_type"];
          cr_number?: string | null;
          api_key: string;
          api_secret: string;
          jwt_secret?: string | null;
          integration_type?: Database["public"]["Enums"]["integration_type"] | null;
          webhook_url?: string | null;
          callback_url?: string | null;
          ip_whitelist?: string[] | null;
          permissions?: Json | null;
          allowed_products?: string[] | null;
          rate_limit_per_second?: number | null;
          rate_limit_per_minute?: number | null;
          rate_limit_per_hour?: number | null;
          monthly_quota?: number | null;
          current_month_usage?: number | null;
          total_assessments?: number | null;
          total_approvals?: number | null;
          pricing_tier?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          billing_details?: Json | null;
          status?: string | null;
          activated_at?: string | null;
          suspended_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n        Update: {\n          id?: string;
          partner_name?: string;
          partner_name_ar?: string | null;
          partner_type?: Database["public"]["Enums"]["partner_type"];
          cr_number?: string | null;
          api_key?: string;
          api_secret?: string;
          jwt_secret?: string | null;
          integration_type?: Database["public"]["Enums"]["integration_type"] | null;
          webhook_url?: string | null;
          callback_url?: string | null;
          ip_whitelist?: string[] | null;
          permissions?: Json | null;
          allowed_products?: string[] | null;
          rate_limit_per_second?: number | null;
          rate_limit_per_minute?: number | null;
          rate_limit_per_hour?: number | null;
          monthly_quota?: number | null;
          current_month_usage?: number | null;
          total_assessments?: number | null;
          total_approvals?: number | null;
          pricing_tier?: string | null;
          contract_start_date?: string | null;
          contract_end_date?: string | null;
          billing_details?: Json | null;
          status?: string | null;
          activated_at?: string | null;
          suspended_at?: string | null;
          created_at?: string | null;
          updated_at?: string | null;\n        };\n      };
      transactions: {\n        Row: {\n          id: string;
          entity_id: string;
          account_id: string | null;
          transaction_type: Database["public"]["Enums"]["transaction_type"];
          amount: number;
          currency: string | null;
          reference_number: string | null;
          description: string | null;
          merchant_name: string | null;
          merchant_category: string | null;
          sender_account: string | null;
          sender_name: string | null;
          receiver_account: string | null;
          receiver_name: string | null;
          transaction_date: string;
          posting_date: string | null;
          value_date: string | null;
          category: string | null;
          is_recurring: boolean | null;
          is_suspicious: boolean | null;
          created_at: string | null;\n        };\n        Insert: {\n          id?: string;
          entity_id: string;
          account_id?: string | null;
          transaction_type: Database["public"]["Enums"]["transaction_type"];
          amount: number;
          currency?: string | null;
          reference_number?: string | null;
          description?: string | null;
          merchant_name?: string | null;
          merchant_category?: string | null;
          sender_account?: string | null;
          sender_name?: string | null;
          receiver_account?: string | null;
          receiver_name?: string | null;
          transaction_date: string;
          posting_date?: string | null;
          value_date?: string | null;
          category?: string | null;
          is_recurring?: boolean | null;
          is_suspicious?: boolean | null;
          created_at?: string | null;\n        };\n        Update: {\n          id?: string;
          entity_id?: string;
          account_id?: string | null;
          transaction_type?: Database["public"]["Enums"]["transaction_type"];
          amount?: number;
          currency?: string | null;
          reference_number?: string | null;
          description?: string | null;
          merchant_name?: string | null;
          merchant_category?: string | null;
          sender_account?: string | null;
          sender_name?: string | null;
          receiver_account?: string | null;
          receiver_name?: string | null;
          transaction_date?: string;
          posting_date?: string | null;
          value_date?: string | null;
          category?: string | null;
          is_recurring?: boolean | null;
          is_suspicious?: boolean | null;
          created_at?: string | null;\n        };\n      };
    };
    Views: {};
    Functions: {};
    Enums: {
      account_type: 'current' | 'savings' | 'investment' | 'credit' | 'loan' | 'digital_wallet' | 'crypto';
      assessment_type: 'personal_loan' | 'business_loan' | 'credit_card' | 'mortgage' | 'auto_loan' | 'overdraft' | 'line_of_credit' | 'bnpl' | 'micro_loan' | 'group_loan' | 'islamic_finance';
      decision_outcome: 'approved' | 'declined' | 'referred' | 'conditional' | 'expired';
      entity_status: 'pending' | 'active' | 'verified' | 'suspended' | 'blacklisted' | 'archived';
      entity_type: 'individual' | 'company' | 'institution' | 'group';
      id_type: 'national_id' | 'iqama' | 'cr_number' | 'tax_id' | 'passport' | 'gcc_id' | 'border_number';
      integration_type: 'api' | 'sdk' | 'white_label' | 'iframe' | 'batch' | 'real_time_stream';
      partner_type: 'bank' | 'nbfi' | 'fintech' | 'bnpl' | 'p2p' | 'microfinance' | 'government' | 'merchant';
      risk_category: 'very_low' | 'low' | 'medium' | 'high' | 'very_high' | 'unscoreable';
      transaction_type: 'credit' | 'debit' | 'transfer' | 'payment' | 'withdrawal' | 'deposit' | 'fee' | 'reversal';
      verification_status: 'unverified' | 'pending' | 'verified' | 'rejected' | 'expired' | 'fraudulent';
    };
  };
} |
